version: '3.8'

services:
  nginx:
    image: nginx
    ports:
      - "8081:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - frontend
      - backend

  frontend:
    image: nginx
    volumes:
      - ./frontend:/usr/share/nginx/html

  backend:
    image: nginx
    volumes:
      - ./backend:/usr/share/nginx/html
